version: '3.0'
services:
  rasa-actions:
    image: rasa/rasa:1.10.3-full
    ports:
      - 5055:5055
    volumes:
      - ./rasa:/app
    entrypoint: rasa run actions
  rasa:
    image: rasa/rasa:1.10.3-full
    depends_on:
      - rasa-actions
    ports:
      - 5005:5005
    volumes:
      - ./rasa:/app
    command:
      - run