version: '3'
services:
  rasa-actions:
    build: .
    volumes:
      - './rasa:/app'
    restart: unless-stopped
    entrypoint: rasa run actions
  chappie-bot:
    build: .
    environment: []
    ports:
      - 5005:5005
    volumes:
      - './rasa:/app'
    restart: unless-stopped
